### ISSUE TITLE
Site request

### ISSUE THREAD

**Issue by CodyKool** [GauthierPoulain/statusBot-issue#1]
Hi, can you add support for the MissionChief.com and MissionChief-australia.com browser games please?

**Comment by GauthierPoulain** [comment]
unfortunately this site does not have a status page or a way to retrieve its status without having to send a ping every X seconds, or I did not find it, if it exists, please send it to me, otherwise i can't add it

**Comment by CodyKool** [comment]
> unfortunately this site does not have a status page or a way to retrieve its status without having to send a ping every X seconds, or I did not find it, if it exists, please send it to me, otherwise i can't add it

Hey, I don't think they have a status page unfortunately. Thanks anyway!
